# Generated by Django 4.0.4 on 2022-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_memory_photo_alter_memory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='points',
            field=models.JSONField(default=None),
        ),
    ]
