# Generated by Django 4.0.4 on 2022-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memory_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='points',
        ),
        migrations.AddField(
            model_name='memory',
            name='point_lat',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='memory',
            name='point_lng',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
