# Generated by Django 4.0.4 on 2022-05-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_memory_points_memory_point_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='comment',
            field=models.TextField(max_length=150),
        ),
    ]
